### ISSUE TITLE
Annoying messages in logs

### ISSUE THREAD

**Issue by kot-begemot-uk** [open-switch/opx-sai-vm#14]
The VM port initialization presently does not implement port speed as well as requests several other attributes which are requested by the upper layers.

As a result the log fills up with messages like this: 

Mar 15 14:29:13 uml-switch opx_nas_daemon[2480]: [ev_log_t_SAI_PORT:Switch Id: 0], Attr get for port id 0x1000000000004's attr index 0 attr id 8 failed with err -65536
Mar 15 14:29:13 uml-switch opx_nas_daemon[2480]: [ev_log_t_SAI_PORT:Switch Id: 0], Attr get for port id 0x1000000000005's attr index 0 attr id 8 failed with err -65536
Mar 15 14:29:13 uml-switch opx_nas_daemon[2480]: [ev_log_t_SAI_PORT:Switch Id: 0], Attr get for port id 0x1000000000006's attr index 0 attr id 8 failed with err -65536
Mar 15 14:29:13 uml-switch opx_nas_daemon[2480]: [ev_log_t_SAI_PORT:Switch Id: 0], Attr get for 
port id 0x1000000000007's attr index 0 attr id 8 failed with err -65536

While these are harmless, they create a considerable amount of background noise making it difficult to follow and trace out any real problems. There seems to be some level of support for obtaining speed and other attributes via ethtool in the python scripts so it looks like some work on this has been done already.

**Comment by atanu-mandal** [comment]
@kot-begemot-uk , sorry for the delayed response. Can you please let us know which version of OPX installer you are using.

The error with supported speed attr (i.e. attr id 8 failed) has been fixed sometimes back. Please refer https://github.com/open-switch/opx-sai-vm/commit/7fde99681f086d0a9b0af3cd9dce49a321587361.

This should be fixed in OPX 2.3.0

There was some discussion in OPX Rocket chat channel as well that you can refer i.e.

https://chat.openswitch.net/channel/opx-vm?msg=uFSSJEfDpBDNppYzG

**Comment by kot-begemot-uk** [comment]
Late pre 2.3.0, local build.

I am rebuilding a checkout of the current git head to verify if it is fixed.

A.

**Comment by jeff-yin** [comment]
Is this still an open issue?

**Comment by Tejaswi-Goel** [comment]
1. Unnecessary log messages issue is solved:  https://github.com/open-switch/opx-sai-vm/commit/9e007ce717de97b7bfece337bf25441821831f00  .  
2. Supported speed attribute issue is solved: https://github.com/open-switch/opx-sai-vm/commit/7fde99681f086d0a9b0af3cd9dce49a321587361

Latest opx installer will not have any above mentioned issues. So this issue can be closed.

**Comment by jeff-yin** [comment]
Thanks!
