### ISSUE TITLE
The script vm_dn_rules.sh is not copied to the target (thus not executed)

### ISSUE THREAD

**Issue by mikelazar** [open-switch/opx-sai-vm#15]
This prevents the L2 packet forwarding to properly happen in a VM environment (and possibly other data traffic functions in OPX VM).

The sai_vm_dn_rules.sh is in the "cfg" directory.

Issue discovered in OPX 2.3.1

Workaround: 
1. Download the file sai_vm_dn_rules.sh from https://github.com/open-switch/opx-sai-vm/blob/master/cfg/vm_dn_rules.sh
2. Copy the file to the OPX VM, and overwrite the contents of the file /usr/bin/dn_rules.sh
3. Execute /usr/bin/dn_rules.sh
Note. /usr/bin/dn_rules.sh is automatically executed at each restart

**Comment by Tejaswi-Goel** [comment]
I will take a look into this.
thanks,
Tejaswi

**Comment by jeff-yin** [comment]
Should be fixed by https://github.com/open-switch/opx-sai-vm/pull/17

**Comment by Tejaswi-Goel** [comment]
**issue solved by commits #17 and #18:**
_**commnd: ebtables -L**_
_**output:**_
Bridge table: filter
Bridge chain: INPUT, entries: 0, policy: ACCEPT
Bridge chain: FORWARD, entries: 3, policy: ACCEPT
-d BGA -j DROP
-p 0x8906 -j DROP
-p 0x8914 -j DROP
Bridge chain: OUTPUT, entries: 2, policy: ACCEPT
-p ARP -o eth0+ --arp-op Request -j ACCEPT
-p ARP --arp-op Request --nflog-group 100 -j ACCEPT
